name: OpenWRT-E8820v2  #设备型号，请用大写字母，请勿乱写

on:
  schedule:
    - cron: 0 22 * * *

  workflow_dispatch:

env:
  OWRT_NAME: E8820v2  #设备型号，请用大写字母，请勿乱写
  OWRT_IP: 192.168.2.1  #设备默认登陆地址
  CORE_TYPE: mips64  #设备内核类型，请用小写字母，请勿乱写
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  LEDE_URL: https://github.com/MoShengQ7/lede.git
  LIST_URL: https://raw.githubusercontent.com/y1292851910/OpenWRT-LEDE/main/Lists

permissions: write-all

jobs:
  build_openwrt:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E rm -rf $(curl -sfL $LIST_URL/Remove.txt)
          sudo -E apt -yqq update
          sudo -E apt -yqq purge $(curl -sfL $LIST_URL/Purge.txt)
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq install $(curl -sfL $LIST_URL/Install.txt)
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq clean
          sudo -E apt -yqq autoclean
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Check Projects
        uses: actions/checkout@v3

      - name: Check Scripts
        run: |
          cd ./Scripts

          chmod +x ./*.sh
          dos2unix ./*.sh

      - name: Clone LEDE Code
        run: |
          git clone --depth=1 --single-branch $LEDE_URL

      - name: Update Feeds
        run: |
          cd ./lede

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom Scripts
        run: |
          cd ./lede
          $GITHUB_WORKSPACE/Scripts/Settings.sh

          cd ./package
          $GITHUB_WORKSPACE/Scripts/Plugins.sh

      - name: Custom Settings
        run: |
          cd ./lede

          rm -rf ./tmp && rm -rf ./.config*
          cat $GITHUB_WORKSPACE/Config/$OWRT_NAME.txt >> .config

          make defconfig

      - name: Download Packages
        run: |
          cd ./lede

          make download -j16

      - name: Compile Firmware
        run: |
          cd ./lede

          make -j$(nproc) || make -j1 V=s

          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./build_dir
          echo "======================="
          du -h --max-depth=1 ./bin
          echo "======================="

      - name: Package Firmware
        run: |
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "OWRT_NAME=$OWRT_NAME" >> $GITHUB_ENV
          echo "OWRT_IP=$OWRT_IP" >> $GITHUB_ENV

          cd ./lede && mkdir ./upload
          rm -rf $(find ./bin/targets/ -type d -iname "packages")
          cp -rf $(find ./bin/targets/ -type f -regex ".*\.\(gz\|bin\|iso\|vmdk\)") ./upload/
          cp -rf ./.config ./upload/config.txt

          cd ./upload
          zip -qm ./"$OWRT_NAME"_Firmware_"$BUILD_DATE".zip ./*.*

      - name: Release Firmware
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.OWRT_NAME}}_Firmware_${{env.BUILD_DATE}}
          files: ./lede/upload/*.zip
          body: |
            不要问，更就完事了！
            地址：${{env.OWRT_IP}}
            密码：password

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 6
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
